# Generated by Django 3.2.5 on 2021-09-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210909_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
