# Generated by Django 3.2.5 on 2021-09-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210910_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercommand',
            name='teacherId',
            field=models.CharField(max_length=20),
        ),
    ]
