# Generated by Django 3.2.5 on 2021-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_teachercommand_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercommand',
            name='name',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachercommand',
            name='orgName',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
