# Generated by Django 3.2.5 on 2021-09-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_teachercommand_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercommand',
            name='password',
        ),
    ]
