# Generated by Django 3.2.5 on 2021-09-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_teachercommand_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercommand',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teachercommand',
            name='teacherId',
        ),
        migrations.RemoveField(
            model_name='teachercommand',
            name='userName',
        ),
        migrations.AddField(
            model_name='teachercommand',
            name='userId',
            field=models.CharField(default='null', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
