# Generated by Django 3.2.5 on 2021-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
