version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'ng serve --open'
    command: 'docker build -t frontend'
    ports:
      - 4200:4200
    # volumes:
    #   - .:/Frontend