# Generated by Django 3.2.5 on 2021-09-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQuery',
            fields=[
                ('teacherId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
