# Generated by Django 3.2.5 on 2021-09-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('orgName', models.CharField(max_length=40)),
                ('aboutMe', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=20)),
                ('fuck', models.CharField(max_length=20)),
            ],
        ),
    ]
