# Generated by Django 3.2.5 on 2021-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherquery',
            name='teacherId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
