# Generated by Django 3.2.5 on 2021-09-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_teacherquery_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherquery',
            name='name',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherquery',
            name='orgName',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
