# Generated by Django 3.2.5 on 2021-09-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_teacherquery_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherquery',
            name='password',
        ),
        migrations.AlterField(
            model_name='teacherquery',
            name='teacherId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
