# Generated by Django 3.2.5 on 2021-09-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210919_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherquery',
            name='password',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
